In [1]:
for i in range(1, 101):
  if i % 15 == 0:
    print("FizzBuzz")
  elif i % 5 == 0:
    print("Buzz")
  elif i % 3 == 0:
    print("Fizz")
  else:
    print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [2]:
import numpy as np

In [3]:
a=np.random.randint(1,11,(3,3))
b=np.random.randint(1,11,(3,3))
print(a)
print(b)

[[ 6  8  2]
 [ 4 10  6]
 [ 5  2  5]]
[[ 9 10  5]
 [10  4  9]
 [ 6  2  7]]


In [4]:
#Addition
a+b

array([[15, 18,  7],
       [14, 14, 15],
       [11,  4, 12]])

In [5]:
#Element wise multiplication
a*b

array([[54, 80, 10],
       [40, 40, 54],
       [30,  4, 35]])

In [6]:
#dot product
np.dot(a,b)

array([[146,  96, 116],
       [172,  92, 152],
       [ 95,  68,  78]])

In [7]:
#det a
print(np.linalg.det(a))

224.00000000000014


In [8]:
import pandas as pd

In [9]:
from google.colab import files

In [10]:
df=pd.read_csv('data_assg1.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data_assg1.csv'

In [ ]:
df

In [ ]:
df.loc[df['value']>=0.7,'Rating']='High'

In [ ]:
df.loc[(df['value']>0.3) & (df['value']<0.7),'Rating']='Medium'

In [ ]:
df.loc[(df['value']<=0.3,'Rating')]='Low'

In [ ]:
df

In [ ]:
df_saved=df[df['Rating']=='Low']

In [ ]:
df=df[~(df['Rating']=='Low')]

In [ ]:
df_saved

In [ ]:
df

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x=np.linspace(-5,5,500)

In [ ]:
y1=x**3+2*x**2+3*x+2
plt.plot(x,y1)
plt.show()

In [ ]:
y2=np.tan(x)/x
plt.plot(x,y2)
plt.show()