In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

Exercise 1: FizzBuzz

In [ ]:
for i in range(100):
    if (i + 1)% 15 == 0:
        print("FizzBuzz")
    elif (i + 1) % 3 == 0:
        print("Fizz")
    elif (i + 1) % 5 == 0:
        print("Buzz")
    else:
        print(i+1)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


Exercise 2: Matrix Operations

In [ ]:
MatrixA = np.random.randint(1, 11, (3, 3))
MatrixB = np.random.randint(1, 11,(3, 3))

print("Addition:")
print(MatrixA + MatrixB)

print("Element-wise multiplication:")
print(MatrixA *MatrixB)

print("Dot product:")
print(MatrixA@ MatrixB)

print("Determinant of matrix A:")
print(np.round(np.linalg.det(MatrixA)))

Addition:
[[13 12  9]
 [14 11 13]
 [11  9 10]]
Element-wise multiplication:
[[30 35  8]
 [45 30 30]
 [10 18 25]]
Dot product:
[[145 109 120]
 [ 87  84  84]
 [ 83  50  86]]
Determinant of matrix A:
210.0


Exercise 3: Pandas Manipulation

In [ ]:
csv = pd.read_csv("https://drive.google.com/uc?id=1OekIEbM6phQNRAZZOfh4optv5Cjh_iQG")

numbertype = []
for value in csv[csv.columns[0]]:
    if value < 0.3:
        numbertype.append("Low")
    elif value < 0.7:
        numbertype.append("Medium")
    else:
        numbertype.append("High")

csv["type"] = numbertype
csv_deleted = []
for i in range(len(csv)):
    if numbertype[i]!= "Low":
        csv_deleted.append(csv[csv.columns[0][i]])

csv_manipulated = pd.DataFrame(csv_deleted)
csv_manipulated.to_csv("final.csv", index=False)
files.download("final.csv")


KeyError: 'l'

Exercise 4: Plotting a curve

In [ ]:
x = np.linspace(-5,5,100)
y1 = x**3 + 2*x**2 + 3 * x + 2
y2 = np.tan(x)/x
y3 = np.linspace(-np.pi,np.pi,100)
x3 = np.sin(y3) + 3*y3

plt.subplot(1,3,1)
plt.plot(x,y1)
plt.subplot(1,3,2)
plt.plot(x,y2)
plt.subplot(1,3,3)
plt.plot(x3,y3)

plt.show()