In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/fruit_production.csv')
df["Total"]=df['Mangoes_ton']+df['Oranges_ton']
df

Region  Temperature_F  Rainfall_mm  Humidity_percent  Mangoes_ton  \
0       A             73           67                43           56   
1       B             91           88                64           81   
2       C             87          134                58          119   
3       D            102           43                37           22   
4       E             69           96                70          103   
5       F             74           66                43           57   
6       G             91           87                65           80   
7       H             88          134                59          118   
8       I            101           44                37           21   
9       J             68           96                71          104   
10      K             73           66                44           57   
11      L             92           87                64           82   
12      M             87          135                57          118   
13      N            103           43                36           20   
14      O             68           97                70          102   

    Oranges_ton  Total  
0            70    126  
1           101    182  
2           133    252  
3            37     59  
4           119    222  
5            69    126  
6           102    182  
7           132    250  
8            38     59  
9           118    222  
10           69    126  
11          100    182  
12          134    252  
13           38     58  
14          120    222

In [ ]:
x1=np.array(df['Temperature_F']/100)
x2=np.array(df['Rainfall_mm']/100)
x3=np.array(df['Humidity_percent']/100)

y1=np.array(df['Mangoes_ton']/100)
y2=np.array(df['Oranges_ton']/100)
y3=np.array(df['Total']/100)

x=np.array([x1,x2,x3])
y=np.array([y1,y2,y3])

n=len(x1)

In [ ]:
a=np.array([0.0,0.0,0.0])
b=0.0
d=np.array([0.0]*3)

def j1(x,y1,a,b,d,n):
  return np.sum((np.dot(a,x)+b-y1)**2)/(n*2)

def dj1(x,y1,a,b,d,n):
  for i in range(3):
    d[i]=np.sum((np.dot(a,x)+b-y1)*x[i])/n
  return

def djb1(x,y1,a,b,d,n):
  return np.sum((np.dot(a,x)+b-y1))/n

lr = 0.01
dj1(x,y1,a,b,d,n)

while(not(abs(djb1(x,y1,a,b,d,n))<10**(-3) and max(abs(d))<10**(-3))):
  dj1(x,y1,a,b,d,n)
  tempb = b - lr*djb1(x,y1,a,b,d,n)
  a = a - lr * d
  b = tempb

print(a,b,j1(x,y1,a,b,d,n))



[-0.40299376  0.88374605  0.57040862] 0.03321338817433401 0.00012031620396344846


In [ ]:
a1=np.array([0.0,0.0,0.0])
b1=0.0
d1=np.array([0.0]*3)

def j2(x,y2,a1,b1,d1,n):
  return np.sum((np.dot(a1,x)+b1-y2)**2)/(n*2)

def dj2(x,y2,a1,b1,d1,n):
  for i in range(3):
    d1[i]=np.sum((np.dot(a1,x)+b1-y2)*x[i])/n
  return

def djb2(x,y2,a1,b1,d1,n):
  return np.sum((np.dot(a1,x)+b1-y2))/n

lr = 0.01
dj2(x,y2,a1,b1,d1,n)

while(not(abs(djb2(x,y2,a1,b1,d1,n))<10**(-3) and max(abs(d1))<10**(-3))):
  dj2(x,y2,a1,b1,d1,n)
  tempb = b1 - lr*djb2(x,y2,a1,b1,d1,n)
  a1 = a1 - lr * d1
  b1 = tempb

print(a1,b1,j2(x,y2,a1,b1,d1,n))


[-0.30887298  0.83274876  0.75518425] 0.05701698072633664 0.00014140893091947292


In [ ]:
a2=np.array([0.0,0.0,0.0])
b2=0.0
d2=np.array([0.0]*3)

def j3(x,y3,a2,b2,d2,n):
  return np.sum((np.dot(a2,x)+b2-y3)**2)/(n*2)

def dj3(x,y3,a2,b2,d2,n):
  for i in range(3):
    d2[i]=np.sum((np.dot(a2,x)+b2-y3)*x[i])/n
  return

def djb3(x,y3,a2,b2,d2,n):
  return np.sum((np.dot(a2,x)+b2-y3))/n

lr = 0.01
dj1(x,y3,a2,b2,d2,n)

while(not(abs(djb3(x,y3,a2,b2,d2,n))<10**(-3) and max(abs(d2))<10**(-3))):
  dj3(x,y3,a2,b2,d2,n)
  tempb = b2 - lr*djb3(x,y3,a2,b2,d2,n)
  a2 = a2 - lr * d2
  b2 = tempb

print(a2,b2,j3(x,y3,a2,b2,d2,n))


[-0.73572512  1.67511093  1.43662091] 0.08548404968482759 0.00018290146141402357


In [ ]:
temp = float(input("Enter the temperature: "))
rainfall = float(input("Enter the rainfall: "))
humidity = float(input("Enter the humidity: "))

temp/=100
rainfall/=100
humidity/=100

print('Mangoes:',(np.dot(a,np.array([temp,rainfall,humidity]))+b)*100)
print('Oranges:',(np.dot(a1,np.array([temp,rainfall,humidity]))+b1)*100)
print('Total:',(np.dot(a2,np.array([temp,rainfall,humidity]))+b2)*100)

Enter the temperature: -200
Enter the rainfall: 0
Enter the humidity: 0
Mangoes: 83.92009140042677
Oranges: 67.47629330402616
Total: 155.69342849949894
